version: 2

dist: dist

project_name: gots

before:
  hooks:
    - go mod tidy

builds:
  - id: gotsl
    main: ./cmd/gotsl
    binary: gotsl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/frjcomp/gots/pkg/version.Version={{ .Version }}
      - -X github.com/frjcomp/gots/pkg/version.Commit={{ .Commit }}
      - -X github.com/frjcomp/gots/pkg/version.Date={{ .Date }}
  - id: gotsr
    main: ./cmd/gotsr
    binary: gotsr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/frjcomp/gots/pkg/version.Version={{ .Version }}
      - -X github.com/frjcomp/gots/pkg/version.Commit={{ .Commit }}
      - -X github.com/frjcomp/gots/pkg/version.Date={{ .Date }}

archives:
  - id: gotsl-archive
    ids:
      - gotsl
    name_template: "{{ .ProjectName }}_gotsl_{{ .Os }}_{{ .Arch }}"
    formats: tar.gz
    format_overrides:
      - goos: windows
        formats: zip
  - id: gotsr-archive
    ids:
      - gotsr
    name_template: "{{ .ProjectName }}_gotsr_{{ .Os }}_{{ .Arch }}"
    formats: tar.gz
    format_overrides:
      - goos: windows
        formats: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .ShortCommit }}"

changelog:
  disable: true
